### ISSUE TITLE
Rsync access request for packages.sury.xyz

### ISSUE THREAD

**Issue by Showfom** [oerdnj/deb.sury.org#1023]
Hello,

We've build mirror service for users in China and I want to request rsync access for `packages.sury.xyz`

Regards,

**Comment by oerdnj** [comment]
`rsync packages.sury.org::repositories`

**Comment by canoine** [comment]
Unfortunately, it seems some symlinks are broken :

```
$ rsync rsync://packages.sury.org/repositories/php/
drwxr-xr-x          4,096 2018/01/24 15:51:34 .
-rw-r--r--            402 2018/11/02 12:40:35 README.txt
-rw-r--r--          2,239 2018/11/02 12:40:35 apt.gpg
lrwxrwxrwx             26 2016/05/19 17:26:45 dists
lrwxrwxrwx             25 2016/05/19 17:26:45 pool
$ rsync rsync://packages.sury.org/repositories/php/dists/
rsync: change_dir "/php/dists" (in repositories) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
rsync: read error: Connection reset by peer (104)
```

**Comment by canoine** [comment]
OK, that works well now. Thank you.

**Comment by Showfom** [comment]
Hi @oerdnj 

Seems the rsync repo did not update for almost two months.

**Comment by Gigelf** [comment]
Hello,

I am trying to make a mirror to use on a closed network but rsync seems not responding..

Regards,

**Comment by Showfom** [comment]
Hi @oerdnj 

Rsync not work after you use CDN, any rsync host now?

**Comment by Showfom** [comment]
@Gigelf please try `rsync rsync://packages.sury.xyz/repositories/`

**Comment by todeveni** [comment]
```
rsync rsync://howl.rfc1925.org/repositories/php/dists/
drwxr-xr-x          4,096 2018/11/14 19:49:21 .
drwxr-xr-x          4,096 2019/03/18 20:06:24 buster
drwxr-xr-x          4,096 2019/03/18 20:13:20 jessie
drwxr-xr-x          4,096 2019/03/18 20:14:32 stretch
```

**Comment by ScarUY** [comment]
> @Gigelf please try `rsync rsync://packages.sury.xyz/repositories/`

Would you be so kind as to ellaborate, or point me in the direction of how to use rsync to install updates? 4 days ago, trying to solve a problem with the signature, some of the nextcloud servers I manage got blacklisted from the repository (403) and unlike it says in https://packages.sury.org/error403.html, the ban hasn't lifted, and I'm unable top update my servers, despite having autoupdate disabled.

**Comment by Gigelf** [comment]
If you are using sury packages with apt, you have to update the gpg key:

apt-key del 95BD4743; wget -nv -O - "https://packages.sury.org/php/apt.gpg" | apt-key add -

**Comment by oerdnj** [comment]
@ScarUY Fill a new issue, providing all the details.  I haven't manually blocked anyone in ages now since the Cloudflare does most of the heavy lifting.

**Comment by ScarUY** [comment]
> If you are using sury packages with apt, you have to update the gpg key:
> 
> apt-key del 95BD4743; wget -nv -O - "https://packages.sury.org/php/apt.gpg" | apt-key add -

I did as for https://packages.sury.org/php/README.txt, but seems that before I managed to found it or while making some mistake while testing it I got banned.

**Comment by ScarUY** [comment]
> @ScarUY Fill a new issue, providing all the details. I haven't manually blocked anyone in ages now since the Cloudflare does most of the heavy lifting.

Thank you for your answer! I think Cloudflare may have got overzealous with my servers, I have blocked all internet access to my servers except for the nextcloud itself, I´ll keep them like that for a couple of days to make sure nothing is triggeting a cloudflare ban, that should solve the issue, in any rate, my question was about how to use rsync as per Showfom answer, I didn't want to waster your time with my issue (not as long as I can manage to solve it by myself, I think is the least I can do with other people's time when they are doing things for me for free), I was expecting something on the lines "go to this site, read this or that" since I wasn't aware of a way to use apt with rsync, and goopgle wasn't very usefull about it, and clearly this is not the right forum to open a question about that.

Thank you again for your time! I'm so used to watch as my questions in forums die of old age without being ever answered, this was refreshing!
