### ISSUE TITLE
Apache 2.4.38 is released

### ISSUE THREAD

**Issue by yildiz-online** [oerdnj/deb.sury.org#1068]
http://www.apache.org/dist/httpd/CHANGES_2.4.38

**Comment by S8Cloud** [comment]
Hoping there will be Debian package of Apache 👍

**Comment by m-ueberall** [comment]
FYI: Due to https://bz.apache.org/bugzilla/show_bug.cgi?id=63052 ("CPU at 100% in process after SSL "scan" that logs as AH02042"), users of Apache 2.4.37/OpenSSL 1.1.1 should be considered in dire need of an update (see also https://blog.qualys.com/ssllabs/2019/01/23/mod_ssl-bug-and-ssl-labs-renegotiation-test) unless there's a watchdog in place...

**Comment by Ayesh** [comment]
@m-ueberall - As a temporary workaround, you can disable TLS 1.0 (or the specific cipher).

**Comment by m-ueberall** [comment]
@Ayesh: If it only affected TLS 1.0, it would be less problematic--however, the Apache 2.4.38 reads as follows:
```
SECURITY: CVE-2019-0190 (cve.mitre.org)
     mod_ssl: Fix infinite loop triggered by a client-initiated
     renegotiation in TLSv1.2 (or earlier) with OpenSSL 1.1.1 and
     later.
```

**Comment by oerdnj** [comment]
Apache 2.4.38-2 uploaded and it's building now.  Sorry for the delay.

**Comment by yildiz-online** [comment]
Installation went smootly, no regression found.

Thank you very much for the great work
