### ISSUE TITLE
Numbering of php-modules, mainly for security concerns

### ISSUE THREAD

**Issue by gplessis** [oerdnj/deb.sury.org#109]
Hi Ondřej,

thanks for your impressive work on php7.0, it's greatly appreciated! Given the faster PHP release cycle, it's definitely a good thing to have a generic framework to build php7.0, php7.1, ... packages and make them installable on the same system.

I have a question about the `pkg-php` and `php-modules` split. It's a definitely a good thing to not build php-modules with every PHP release with the same `phpapi`. But I don't think having `php-modules` - numbered `7-something` - built once at the beginning of the lifecycle of a major PHP branch is a viable solution in the long term when it dealing with security.

Security updates happen on PHP modules too. So should `php-modules`be rebuilt every time a security issue has been fixed in a module, with a relevant version number (`7.0.4-something`, for instance)? The benefits of having the `pkg-php`/`php-modules` split are then smaller than expected :(

Maybe you have another solution. Could you please explain a bit more what is planned for `php-modules`, especially in terms of numbering?
And how do you deal with a Debian/Ubuntu release with two branches of PHP - let's say php7.0 and php7.1, both with different `phpapi`? `php-modules` should then generate duplicated versions of the same packages, right? Or is there a way do deal with the `Built-Using` package property?

Thanks in advance for your answer.

**Comment by oerdnj** [comment]
Hi,

(as a side note I will have to start documenting the new plan into some wiki soon)

the main src:php-modules will get rebuilt every time there's a new supported php release. Debian (and I am guessing Ubuntu as well) will want to support only one PHP release at the time, but since you are using my PPA, you know I am supporting more than one major.minor release at the same time.

E.g. if there's a new PHP 7.0.x release, the php-modules will pull new php7.0-modules-src package and rebuild the modules. Also if there's a new PHP 5.6 release the same will be done. So you will always get the latest releases modules matching the major.minor release.

 I will indicate the sources used to rebuild in the description of the package (or something like that).

Cheers,
Ondrej

**Comment by AnrDaemon** [comment]
I do not understand your obsession with running different PHP versions on the same system.
What Docker/LXC/LXD do not offer to you that you absolutely need to hog your system with multiple different versions of the same package?
Keep your system clean and it'll repay you in clean work.

**Comment by oerdnj** [comment]
src:php-modules has been dropped in favor of building all modules from src:phpX.Y
