### ISSUE TITLE
AAAA record for packages.sury.org timeout from the IP address <::> in the network <> in the AS <ASN>

### ISSUE THREAD

**Issue by working-name** [oerdnj/deb.sury.org#1132]
**Describe the bug**
I realize IPv6 is not yet a thing given stubborn, annoying ISPs around the world, but just thought you should know: Your AAAA records are active, but any connection attempt is simply not responded to which leads to horribly long timeouts. `apt` will give priority to ipv6 like most other tools these days, so it's rather awkward.

**To Reproduce**
1. Add php repo
2. Run apt update
3. Wait forever

**Expected behavior**
Repo files should be served via IPv6 too, if there's a AAAA record assigned to the same subdomain

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository: packages.sury.org

Workaround:
`apt -o Acquire::ForceIPv4=true ...`

**Comment by oerdnj** [comment]
Sigh. How do you think one can debug a network problem (like take it to the CDN provider) if you don't provide **any** information about your client network? Would it be that hard to provide ASN and source network?

**Comment by working-name** [comment]
Yeah, no... I was trying to help, not find yet another know-it-all with an attitude. Have fun, buddy.

**Comment by oerdnj** [comment]
No, you weren’t trying to help. You just claimed that the IPv6 doesn’t work, but it doesn’t work for **you**. To debug a networking issue, one need to know both sides of the connection. By not providing the needed information, you wasted my time, which is very much precious, and your time.

**Comment by marka63** [comment]
@working-name the first step in debugging network issues is provide the ip addresses involved.  The second and third steps are trace routes and packet traces.

This lets one know where routing is broken and if routing is not broken whether the TCP connection is established or not.  If routing is broken apt should be falling back to the other addresses.  If the TCP connection is established then the problem could be PMTUD is failing.  You symptoms match both of these scenarios.  "Not responded to" could mean multiple things depending upon  the level of understanding of the reporter.

Since you don't want to give @oerdnj your IP address open a ticket with your ISP.
