### ISSUE TITLE
PHP PGO Support

### ISSUE THREAD

**Issue by rohanvakharia** [oerdnj/deb.sury.org#1194]
Is there any way I can do use profile guided optimization via PPA installation?

**Comment by joglomedia** [comment]
@rohanvakharia i think not possible, because PGO will requires you to train the compiler first to produce a more optimized result. As below

```
$ make prof-gen
```

This will create a binary of PHP which generates a profile. You need to run this version of php with some workload which is representative of the web site you are building. For example, you can use Wordpress if this is representative of the site you are running. Then, you need to recompile php using the profile you just generated, with

```
$ make prof-use
```

#cmiiw
