### ISSUE TITLE
Update xdebug

### ISSUE THREAD

**Issue by Jamesking56** [oerdnj/deb.sury.org#1286]
XDebug 2.8.0 has a critical bug that affects code coverage runtimes in CI ([link here](https://bugs.xdebug.org/view.php?id=1717)).

XDebug 2.8.1 was released to fix this. When will the PPA update the XDebug versions?

**Comment by oerdnj** [comment]
> When will the PPA update the XDebug versions?

Well, I don't know. Do you have a support contract? Or did you at least asked nicely?

**Comment by Jamesking56** [comment]
Its just been updated now

**Comment by Jamesking56** [comment]
Is this automated or is it going to be manual every time? Can we get GitHub actions to build it please?

**Comment by oerdnj** [comment]
> Can we get GitHub actions to build it please?

Sure, send the code / MR. It needs to support:
* merging the multiple sources into one debian orig.tar.xz because of PHP 5 vs PHP 7 (for some packages like xdebug)
* importing the newly built sources with `gbp import-orig`
* refreshing the patches using gbp pq (if there are any)
* updating the debian/changelog to new upstream version with `gbp dch`
* building the source packages for Ubuntu and uploading them to launchpad (with modified `ubuntu-build` to support different delimiter)
* pushing the update git tree to the repository
* triggering the Debian source and binary jobs in the Jenkins for the respective package
* tagging the new release (if everything went well in previous steps)

**Comment by Jamesking56** [comment]
I can make an MR if you share the manual steps you take to build these packages? Or is that a secret?

I'm not trying to be rude, I'm trying to make this PPA better and more automated for you to benefit the community

**Comment by oerdnj** [comment]
The extra packaging tools are here: http://salsa.debian.org/ondrej/packaging-tools.git

**Comment by oerdnj** [comment]
The rest is standard debian (`gbp-buildpackage`)

**Comment by Jamesking56** [comment]
@oerdnj Thanks for that and thanks for all the work you have done for this PPA.

My aim here is to essentially automate the process using GitHub actions (free for open source) to save your time and help the community by making the PPA updates automated. I'm not a PPA creator, I just simply would like to improve this repository.

Can you please provide the specific steps, one by one, to me so I can formulate a set of GitHub actions / Docker instructions in order to automate those steps? Thanks.

**Comment by oerdnj** [comment]
> Can you please provide the specific steps, one by one, to me so I can formulate a set of GitHub actions / Docker instructions in order to automate those steps?

No, I can't. I simply don't have time for this.
