### ISSUE TITLE
apache2-data breaking apache2

### ISSUE THREAD

**Issue by marcostrullato** [oerdnj/deb.sury.org#1377]
Hi all,

every day my systems check and install updates, and I have the sury repo configured from where I get php and, apache.
Today the package apache2-data got updated and it broke apache2: now my webserver is dead!
I'm not sure where to file the bug, but it's certainly something wrong.

Suggestions?
Did anyone experiencing the same issue?

I'm trying to fix the issue, but so far no luck.
(I've initially opened a bug at [here](https://bugs.launchpad.net/apache2/+bug/1873695), but I realized then it's more appropriate this issue tracker.)

My system is a raspberry pi 4 with 4GB RAM, with raspbian buster.

From the apt history:

```
Start-Date: 2020-04-19 12:48:29
Commandline: apt-get -y install apache2-data
Upgrade: apache2-data:armhf (2.4.41-2~20190819.8+debian10, 2.4.43-1+0~20200419.9+debian10~1.gbp912f29)
Remove: python3-certbot-apache:armhf (0.31.0-1), python-certbot-apache:armhf (0.31.0-1), apache2:armhf (2.4.41-2~20190819.8+debian10)
End-Date: 2020-04-19 12:48:40
```

When I try to reinstall apache2 I get:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2 : Depends: apache2-data (= 2.4.41-2~20190819.8+debian10) but 2.4.43-1+0~20200419.9+debian10~1.gbp912f29 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Kernel:
`Linux iot 4.19.97-v8+ #1294 SMP PREEMPT Thu Jan 30 13:27:08 GMT 2020 aarch64 GNU/Linux`

Shared C library:
`Version: 2.28-10+rpi1`

**Comment by marcostrullato** [comment]
For who is reading, in order to restore the webserver I did:

- ensure I have installed apache2-data and its dependencies
- apt-get download apache2
- dpkg -i --force-all ./apache2_2.4.41-2~20190819.8+debian10_armhf.deb

Cheers

**Comment by marcostrullato** [comment]
I had to disable the sury repo and switch back to the native buster - pity.

Cheers

**Comment by Neocramencer** [comment]
Got the same issue on my raspberry pi 3. was always working but the last update break the apache2. I also reverted back to the buster apache.

Can you please fix this? I want the newer version again.

The following packages have unmet dependencies:
 apache2 : Depends: apache2-data (= 2.4.41-2~20190819.8+debian10) but 2.4.43-1+0~20200419.9+debian10~1.gbp912f29 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by oerdnj** [comment]
As far as I can see, the apache2 packages were built for amd64, i386, armhf and amd64 now.

**Comment by Neocramencer** [comment]
@oerdnj 

Well maybe i get you wrong but i did a new apt-get update before and issue is still the same:

root@raspberrypi:~# apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
Holen:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
OK:3 https://packages.sury.org/apache2 buster InRelease
OK:4 https://packages.sury.org/php buster InRelease 
Holen:5 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB]
Holen:6 http://raspbian.raspberrypi.org/raspbian buster/contrib armhf Packages [58,7 kB]
Holen:7 http://raspbian.raspberrypi.org/raspbian buster/non-free armhf Packages [103 kB]
Es wurden 13,2 MB in 14 s geholt (916 kB/s).           
Paketlisten werden gelesen... Fertig
root@raspberrypi:~# apt upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete sind zurückgehalten worden:
  apache2-bin apache2-data apache2-utils
Die folgenden Pakete werden aktualisiert (Upgrade):
  base-files distro-info-data iputils-ping libapr1
  libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
  libcups2 libldap-2.4-2 libldap-common libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 tzdata
  wpasupplicant
15 aktualisiert, 0 neu installiert, 0 zu entfernen und 3 nicht aktualisiert.
Es müssen noch 2.246 kB von 2.449 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 81,9 kB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n] n
Abbruch.
root@raspberrypi:~# apt-get dist-upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  apache2-bin apache2-data apache2-utils libapr1
  libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
  liblua5.2-0 ssl-cert
Verwenden Sie »apt autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  apache2
Die folgenden Pakete werden aktualisiert (Upgrade):
  apache2-bin apache2-data apache2-utils base-files
  distro-info-data iputils-ping libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libcups2
  libldap-2.4-2 libldap-common libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 tzdata
  wpasupplicant
18 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 2.246 kB von 4.020 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.327 kB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n]

**Comment by oerdnj** [comment]
@Neocramencer There's no information I can work with in the comment you just added, please use the Bug report template to fill out important information:

https://github.com/oerdnj/deb.sury.org/issues/new?assignees=&labels=&template=bug_report.md&title=

(Just copy&paste the template here, don't create new issue.)

**Comment by Neocramencer** [comment]
**Describe the bug**

I try to describe as best as i can in english. I always used your debian repository for apache and php. I tryed to update to the latest packages and the issue was that it broke the apache.

I cannot reproduce the behavior before anymore but the current issue. I reverted back to buster apache2:

Server version: Apache/2.4.38 (Raspbian)
Server built:   2019-10-15T19:53:42

I want now to upgrade to the apache2 in your repository again but that will not work because it will remove the apache2 completely because of some unmachting dependencies with apache2-data.


**To Reproduce**
Steps to reproduce the behavior:
1. Raspbian on Raspberry Pi 3 (buster) (4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l)

2. apt-get update fro mthe following sources:

root@raspberrypi:~# apt-get update
OK:1 http://archive.raspberrypi.org/debian buster InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 https://packages.sury.org/apache2 buster InRelease
OK:4 https://packages.sury.org/php buster InRelease
Paketlisten werden gelesen... Fertig



3. apt-get upgrade (will exclude the apache2 because of some unmet dependencies).

root@raspberrypi:~# apt-get upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete sind zurückgehalten worden:
  apache2 apache2-bin apache2-data apache2-utils
Die folgenden Pakete werden aktualisiert (Upgrade):
  base-files distro-info-data iputils-ping libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libcups2 libldap-2.4-2 libldap-common libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 tzdata wpasupplicant
15 aktualisiert, 0 neu installiert, 0 zu entfernen und 4 nicht aktualisiert.
Es müssen noch 2.246 kB von 2.449 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 81,9 kB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n]

4. apt-get dist-upgrade (will remove apache2)

root@raspberrypi:~# apt-get dist-upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.2-0 ssl-cert
Verwenden Sie »apt autoremove«, um sie zu entfernen.
Die folgenden Pakete werden ENTFERNT:
  apache2
Die folgenden Pakete werden aktualisiert (Upgrade):
  apache2-bin apache2-data apache2-utils base-files distro-info-data iputils-ping libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libcups2 libldap-2.4-2 libldap-common libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
  tzdata wpasupplicant
18 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 2.246 kB von 4.020 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.327 kB Plattenplatz freigegeben.


**Expected behavior**
Behavior would be to upgrade from buster standard apache2 to most recent version

**Distribution (please complete the following information):**
 - OS: 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
 - Architecture: Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
 - Repository: packages.sury.org PHP and Apache2


Output of `apt-cache policy apache2:

root@raspberrypi:~# apt-cache policy apache2
apache2:
  Installiert:           2.4.38-3+deb10u3
  Installationskandidat: 2.4.41-2~20190819.8+debian10
  Versionstabelle:
     2.4.41-2~20190819.8+debian10 500
        500 https://packages.sury.org/apache2 buster/main armhf Packages
 *** 2.4.38-3+deb10u3 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status

root@raspberrypi:~# apt-cache policy apache2-data
apache2-data:
  Installiert:           2.4.38-3+deb10u3
  Installationskandidat: 2.4.43-1+0~20200419.9+debian10~1.gbp912f29
  Versionstabelle:
     2.4.43-1+0~20200419.9+debian10~1.gbp912f29 500
        500 https://packages.sury.org/apache2 buster/main armhf Packages
 *** 2.4.38-3+deb10u3 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status

**Additional context**
In my opinion this is an issue with the repository because the apache2-data is already on 2.4.43 and apache2 still on 2.4.41.


Hope this is now better to resolve this issue ;)

**Comment by oerdnj** [comment]
I see, thanks.  This (the `apt-cache policy`) makes it much easier to debug.

**Comment by oerdnj** [comment]
You can watch the progress here: https://jenkins.rfc1925.org/job/apache2_apache2-binaries/9/
