### ISSUE TITLE
Request to include the php threads extension within php5 ppa

### ISSUE THREAD

**Issue by rivimey** [oerdnj/deb.sury.org#139]
We would like to use the threads API for php5, but it's been hard to get integrated. Is there a chance to add a compiled extension as part of your PPAs?

**Comment by deeky666** [comment]
:+1:

**Comment by robfrawley** [comment]
You talking about threads.io or pthread? If you talking about pthreads you should use the search function of the GitHub issue tracker...

See: https://github.com/oerdnj/deb.sury.org/issues?utf8=%E2%9C%93&q=is%3Aissue+pthreads

That said, I would also love pthreads support, which is why I have been taking as much time as possible to put aside a bit of my work time make it happen against these (sury's) package sources.

You can check out progress here: https://launchpad.net/~scribeinc/+archive/ubuntu/php5-zts

At this time, all the packages listed there are quite literally sury's package source's compiled against the main PHP package shown, which had the needed flags enabled, so they work fine, though I would not recommend a production enviornment until I have time to finish (and automate) the process of grabbing all of sury's source packages, making the required changes, and pushing them up. At the moment, if you needed any extension not listed there you would have to use pecl.

Hopefully I'll have time in the (nearish) future.

**Comment by rivimey** [comment]
Hi rob, thank you for your time and for writing this up. I will have a look around what you've done.

**Comment by robfrawley** [comment]
@oerdnj: Do you have any automation methods you use and/or advice as to more efficient build procedures?

I've confortable with the entire (basic) build process for debs now (which I'd learned about for Nginx last year). I'm in no way new to compilation, but debs are a brand new terrain for me. ;-)

As it stands, I'm currently using simplesbuild to test builds in a sterile environment instead if flooding launchpad with failing builds).

As for actually building, its just tedius: add your ppa, grab your source package, edit anything required (generally there is no need to edit anything once the main php package has had the needed flags added to the package rules so the source is configured for ZTS), run dch -i (and pretend I have any useful understanding of the crazy version strings deb packages are given --- just hope I'm doing it right so that my package gets priority over yours on a machine with both PPAs), call debuild if I'm crazy confident followed by dput, though, as mentioned I try to utilize simplesbuild often as its proven helpful...

Repeat for every dam PHP package...

But yeah, any thoughts or advice? The company I work for requires ZTS now, so I'd like to use the oportunity to be sure ither can use it too, versus just locally building your edited packages for myself.

This is long term, so I'll be the tiny shadow behind you using your amazing work (and much appreciated---been using your PPAs for so long I can't remember, and for a long time, your PPA was a godsend due to the slow momentum behind bumping each minir PHP release in the offical Ubuntu repos at times---though they have been much quicker more recently compared to say...moving from 5.2 to 5.3, which took then forever---anyway, point is, thanks ). 

So the goal is to develop a well defined method to handle this, using your work as a foundation for the small percentage of people who seek out ZTS enabled PHP builds.

For instance, i know you have no intention of releasing the packages due to your past GitHub messages, and I respect that, but your experience would be very beneficial --- example: is this a situation that warrents actually changing the name? For example "php5-zts", " php5-zts-igbinary", etc? And that's one of 50 questions I'd like to get your thoughts on. 

Hang out on IRC anywhere? If so I am rmf on efnet, robfrawley on freenode.

**Comment by oerdnj** [comment]
@robfrawley look at the new PHP 7.0 (master-7.0 branch; most up-to-date) + PHP 5.6 (php-5.6 branch) + master (just generic packaging) branch package, it should be much easier to do such changes in the new debian/rules.

Dropping your override stuff into debian/rules.d/ + override PHP_NAME_VERSION, regenerate debian/control (`debian/rules debian/control`) and you should be mostly done. You should definitely add +zts to phpapi variable.

As for the extensions, there's work yet to be done in the pkg-php-tools territory, but once it's done it should compile for your PHP versions automagically (at least this is the grand plan to pull the supported version by running phpquery -V and building the extension for all of the returned versions).

**Comment by oerdnj** [comment]
Folks, if you want to shoot yourself in foot, the new packaging infrastructure I built for PHP 7.0 allows to build variants quite easily, so here's experimental, totally unsupported PPA with PHP 7.0 ZTS: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts

No external modules, no batteries, no support (patches accepted and welcomed). (e.g. you'll have to build threads PECL extension from source).
