### ISSUE TITLE
Is the Imagick release a fork?

### ISSUE THREAD

**Issue by Danack** [oerdnj/deb.sury.org#1502]
This doesn't fit into either a bug report or feature request, so not going to fill out the template.

fyi - typo in "Frequenty Asked Questions". I guess it is close to "noel' time of year.

**Comment by oerdnj** [comment]
I have no idea what you are asking? Even without a template you need to be verbose.

**Comment by Danack** [comment]
I'm the maintainer of the Imagick extension.

Is the published package available through your repo officially a fork? Are you going to be using the same version numbers as upstream? Are you going to be continuing to pull changes from upstream, or will you be fixing bugs yourself in this package.

**Comment by oerdnj** [comment]
It's not a fork. It's normal downstream distribution package - it contains the base tarball and set of patches that the maintainer of the package considers to be necessary for the distribution. This has always been a case for all the packages in Debian, Ubuntu, Fedora and others.

In fact, @remicollet does the same for the Fedora: https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-imagick.git/tree/

**Comment by oerdnj** [comment]
Same goes for Arch Linux: https://github.com/archlinux/svntogit-community/blob/packages/php-imagick/trunk/PKGBUILD (it pull the PR 296 into the package).

I still don't get your question.

**Comment by oerdnj** [comment]
@Danack, I've now read the https://github.com/Imagick/imagick/issues/358, so I understand where are you coming from. I think your anger is misdirected here. I also have my share of entitled people **demanding** stuff to be done and yelling at me, so we are basically in the same boat. I would be also happy to share your plea to get more GitHub sponsors to my followers both on Twitter and in my Patreon newsletter, and I believe that @remicollet would be also happy to do so.

As for the way PHP 8.0 support in added to the package, I think that I can be more precise and split the PHP 7.x version and PHP 8.x version of imagick extension in the package, so the PHP 7.x is not affected by the patches, if you believe the PHP 8.x patch is too intrusive.

I am now closing the issue here, but I would be happy to continue the conversation in DM or email, ok?

**Comment by oerdnj** [comment]
FYI I've also had people emailing my employer and complaining about what I do in my free time and my reactions to their abusive behaviour, here's a fine example: https://twitter.com/oerdnj/status/1223583649020481536?s=20
