### ISSUE TITLE
[zstd] update to 1.4.9 on Ubuntu

### ISSUE THREAD

**Issue by al-cheb** [oerdnj/deb.sury.org#1573]
**Describe the solution you'd like**
zstd 1.4.9 provides significant performance improvements - https://www.phoronix.com/scan.php?page=news_item&px=Zstd-1.4.9-Released

**Distribution (please complete the following information):**
 - OS: Ubuntu
 - Architecture: amd64
 - Repository: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Package(s) (please complete the following information):**
```
# apt-cache madison zstd
zstd | 1.4.8+dfsg-2+ubuntu16.04.1+deb.sury.org+4 | http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages

```

**Comment by fcorriga** [comment]
zstd 1.5.0 is even faster

**Comment by AzureRaptor** [comment]
This PPA is a wonderful resource, and I'm grateful to the creator/maintainer for making it happen.

On zstd:
Agreed.  It's been **_more than two years_** since this was opened, and zstd is up to 1.5.2 now - and that was just the last time I checked.  It would be _wonderful_ if we could get updated to current.

I've put in a donation via paypal to deb.sury.org.  It's not much, but hope it helps.
