### ISSUE TITLE
The "unknown" status of PHP packages in apt output

### ISSUE THREAD

**Issue by victor-sudakov** [oerdnj/deb.sury.org#1579]
The apt output on Debian 10 AMD64 (buster) shows the PHP packages with the "unknown" suffix, e.g.

```
$ apt list php7.4-redis
Listing... Done
php7.4-redis/unknown,now 5.3.2+4.3.0-7+0~20210228.34+debian10~1.gbp893bd4 amd64 [installed,auto-removable]

```
This probably means the repository doesn’t have a “Suite” entry in its Release file. Would it be possible to add the "Suite" entry or find another way to get rid of the "unknown" suffix? The question is of course mostly cosmetic.

I'm using the following repo:
`deb https://packages.sury.org/php/ buster main`

**Comment by oerdnj** [comment]
Yeah, there was a problem before that for repositories without `Signed-By` you could not do the change because it would require manual confirmation, so it was a two phase process where I had to add `Signed-By` and then wait some time...  which now definitely passed, so I have also added `Suite` now.

**Comment by victor-sudakov** [comment]
Thank you Ondřej!
