### ISSUE TITLE
Sessions, php-imagick, php-mcrypt

### ISSUE THREAD

**Issue by zuiguniang** [oerdnj/deb.sury.org#161]
Sessions:
Tue Dec 08 21:17:35.117234 2015] [:error] [pid 7113] [client a.b.c.d:49287] PHP Catchable fatal error:  session_regenerate_id(): Failed to create(read) session ID: user (path: /var/lib/php/sessions) in ...

php-imagick:
Setting up php-imagick (3.4.0~rc2-1+deb.sury.org~trusty+5) ...
dpkg: error processing package php-imagick (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 php-imagick
E: Sub-process /usr/bin/dpkg returned an error code (1)

php-mcrypt:
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0

**Comment by Sopsys** [comment]
The same happens with php-apcu.

Setting up php-apcu (5.1.2-1+deb.sury.org~trusty+1) ...
dpkg: error processing package php-apcu (--configure):
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
php-apcu
E: Sub-process /usr/bin/dpkg returned an error code (1)

Can be fixed by commenting all lines out in /var/lib/dpkg/info/php-apcu.postinst, running apt-get dist-upgrade and enabling the module manually, eg. echo "extension=apcu.so" > /etc/php/7.0/fpm/conf.d/20-apcu.ini

**Comment by Sopsys** [comment]
Can also duplicate for php-xdebug. The culprit and fix is the same as above.

**Comment by oerdnj** [comment]
Better quick fix is to add another ALL to php_invoke call, e.g `php_invoke #HELPER# ALL ALL $conf || #ERROR_HANDLER#`.

But I have just uploaded fixed dh_php, so only rebuild of affected modules is needed to fix this.

**Comment by oerdnj** [comment]
Anyway +2 of apcu and xdebug and +6 of imagemagick are rebuilt versions with fixed postinst code.

**Comment by Sopsys** [comment]
Thanks for the info, can confirm it works now.

**Comment by oerdnj** [comment]
@zuiguniang As for the session issue, please follow the "one issue per bug" rule. You will have to provide more info than incomplete log line anyway.
