### ISSUE TITLE
Redis for 5.6 from parallel PPA 5.6/7.0?

### ISSUE THREAD

**Issue by mfn** [oerdnj/deb.sury.org#173]
I've successfully running PHP 5.6/7.0 in parallel from https://launchpad.net/~ondrej/+archive/ubuntu/php  on trusty 64bit.

However I can't seem to find the redis extension for 5.6; installing `php-redis` only installs a `redis.so` in the `/usr/lib/php/2015.....` folder for PHP7, but not in `/usr/lib/php/2013....`?

(I've the same problem with the xdebug package).

**Comment by oerdnj** [comment]
This is still work in progress. The main problem is that most of the php7 versions of extensions doesn't support versions < 7.0. I'll have to see yet if this is a common pattern (as in apcu) or just not enough time on the author side to make the correct #ifdefs in the right places. I really don't want to have a versioned 3rd party modules as a lot of things breaks when there's a new minor version of PHP (you have to rename all the modules).

**Comment by mfn** [comment]
Sorry for my lack of knowledge, but for this example with redis, you built a module for 5.6. Can this binary be used with the 5.6 version of this repo?

Btw, thank you very much for your hard work and dedication for providing all these packages and in a timely manner!

**Comment by oerdnj** [comment]
The problem is that building separate versions need a separate source packages, and each time a new PHP minor version (say 7.1) is released, you need to produce a new source package, which is quite a hassle (in Debian), instead of just updating the source code.

So I am thinking of a way how to circumvent this and have just one source package that would either include a source code that supports both versions or multiple source codes. I'll come with some solution sooner or later :)

**Comment by mfn** [comment]
Understood 😀 Thank you!

**Comment by oerdnj** [comment]
Uploading php-redis_2.2.7-355-g799e0bc+2.2.7-1+deb.sury.org~*+1.dsc: done
