### ISSUE TITLE
Debian Stretch LTS End of Life

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#1785]
By the end of June 2022, the [Debian Stretch LTS](https://wiki.debian.org/LTS) has [reached the end-of-life for LTS](https://lists.debian.org/debian-lts-announce/2022/07/msg00002.html) and it has been switched to [Extended LTS](https://wiki.debian.org/LTS/Extended) mode.

The PHP packages for Debian Stretch as available from DEB.SURY.ORG are no longer built and published. All packages have been completely removed on 2. July 2022.

If you absolutely need PHP packages past for the Debian Stretch ELTS and upgrade to Debian buster or (even better) Debian bullseye is not an option for you, the availability of the packages from the [PHP LTS by Freexian](https://php.freexian.com) will be unaffected and you can get PHP packages for Debian ELTS as a paid option.

**Comment by oerdnj** [comment]
Just a forewarning - because it happens every time the distribution goes EOL, I will not discuss any requests such as:
- could you "just keep it there"
- could you "extend it by just a couple of days"
- etc...

The end-of-life for Debian Stretch LTS was announced years ago and is well known. It's also well known that this repository does not provide packages beyond the lifetime of the base distribution.

Also, if you are going to be rude, you will be blocked and banned.

**Comment by oerdnj** [comment]
This is happening now...

**Comment by Monter** [comment]
Behavior worthy of a pain in the ass. Thanks

**Comment by oerdnj** [comment]
The emails from GitHub does have headers identifying the rude person `X-GitHub-Sender: Monter` ... just saying.

**Comment by douglasduarte** [comment]
I have a serious problem, is there any place where I can get the list for stretch?

**Comment by waja** [comment]
I would guess "no": https://github.com/oerdnj/deb.sury.org/issues/1785#issuecomment-1166213005

**Comment by oerdnj** [comment]
It's right at the top:

> If you absolutely need PHP packages past for the Debian Stretch ELTS and upgrade to Debian buster or (even better) Debian bullseye is not an option for you, the availability of the packages from the [PHP LTS by Freexian](https://php.freexian.com/) will be unaffected and you can get PHP packages for Debian ELTS as a paid option.

**Comment by kanlukasz** [comment]
Oh, that's probably why I have errors like `E: The repository 'https://packages.sury.org/apache2 stretch Release' does no longer have a Release file.` when trying to use `sudo apt update`

Ok, so is it possible to safely upgrade `9.13 stretch` to `bullseye` in simple way?
Do I have to uninstall Apache and PHP deb.sury first?
Or should I do it in a different way?

**Comment by oerdnj** [comment]
Debian doesn't support skipping releases, so you need to go via Debian Buster. Removing the packages from external repositories should not be necessary, but you need to update the sources.list files together.

**Comment by lk77** [comment]
I think it's a bad practice to unpublish anything, i understand that stretch is not supported anymore and you don't provide newer versions, but unpublishing old versions, it's another story

**Comment by r4dius** [comment]
> I have a serious problem, is there any place where I can get the list for stretch?

Months later but : https://debian.octopuce.fr/snapshots/sury-php/

**Comment by WagnerGMD** [comment]
`deb https://debian.octopuce.fr/snapshots/sury-php/20220630010404/ stretch main >> /etc/apt/sources.list;`
Thank you @r4dius but there is a little drawback with this repository about the php sic... As you can guess, for the moment this the latest folder which can provide the package (such as php8.1-fpm, php7.4-fpm etc)
```
apt update;
apt show php7.4 php8.0 php8.1 php8.2 | egrep 'Version|APT-Sources';
```

- https://www.php.net/supported-versions.php
- https://wiki.debian.org/LTS/Extended
- https://debian.octopuce.fr/snapshots/sury-php/20220630010404/dists/
- https://debian.octopuce.fr/snapshots/sury-php/20220630010404/dists/stretch/
- [An image which resume](https://www.zupimages.net/viewer.php?id=22/26/wdxy.png) (in a table) the support about each version of Debian
- https://unit.nginx.org/news/2022/ No way ! That's sound a terrible bad idea (we want something simple (avoid Docker)) sic...
- https://nginx.org/en/CHANGES (as today the mainline version = "1.23.1")
- https://nginx.org/en/linux_packages.html  Bad news recently I had discover there is only a support for "bullseye" sic...
- https://github.com/u-sb/nginx-source So If you have the knowledge, open an issue (or a pull request) !
- https://mirror-cdn.xtom.com/sb/nginx/#stretch  Could we trust them ? Because no It doesn't work sic...
- https://n.wtf/install.html#unsupported-os 

Somebody is able to find (or to provide) the same thing for nginx ? **Because we need another repository !**
Unless someone has an idea (which words to use or is able) to contact the people which provide the support for these repositories ? From my point of view, it's sound very hard to change the opinion (about the drop for stretch) sic...

For a bunch a people, I can confirm @lk77 we are totally agreed ! Specially because that's really a bad practice and a huge number will keep to use Stretch (aka Debian 9) for a long moment (as we can see (on the picture above) **the ELTS remain until July 2027**).

PS : Another reason ? It's totally clean so we can install directly the latest python (current version = 3.10.7).
The next one ? Perhaps we can excepted the same thing for Debian 12 (aka bookworm; unless we had to wait a few years).
