### ISSUE TITLE
PHP 8.2 Mcrypt is missing

### ISSUE THREAD

**Issue by lukasneubauer** [oerdnj/deb.sury.org#1901]
Hello Ondřej,

first of all, thank you for the work you do for the PHP community.

Durring the installation of PHP 8.2 from your PPA I have found possible bug / missing feature, that php8.2-mcrypt package is missing and has no installation candidate, although php 5.6 - 8.1 all have this extension.

Best regards,

Lukáš

**Comment by jbcr** [comment]
Hello,

Mcrypt is deprecated! Why continue to use it?

Using this extension is dangerous for your system and all data stored on it.

Like the GDPR in Europe, many countries have a law to increase personal data security. 

MCrypt is not in the "state of the art" of IT security. It uses old and insecure ciphers. Using it must be only to convert the data to secure cipher.

Best regards,

**Comment by oerdnj** [comment]
Now tell me - why do you think I have setup the issue templates? The issue is missing the crucial information - where it is missing. Is it Ubuntu? Is it Debian? What Ubuntu/Debian release? The issue templates are there not for my entertainment, but to save time on both side. By properly filling the bug report, I wouldn't have to ask and you wouldn't have to respond, because the information would already be in the issue here.

**Comment by lukasneubauer** [comment]
Hello Ondřej,

please, forgive me for my incomplete issue. Next time I will try to create it with all the necessary information right from the start.

Here is the missing info:

- OS: Ubuntu 20.04
- Architecture: amd64
- Repository: Ubuntu PPA

During the installation of php8.2-mcrypt the apt-get says, that there is  no installation candidate for this package.

I know mcrypt is deprecated since PHP 7.1 and removed from PHP since 7.2, but in your PPA there is mcrypt not just for PHP 7.1 and 7.2, but also for 7.3 - 8.1, so I was wondering if this just a missing feature and the package was not included by mistake or if this was your intention to leave the package out.

Once more, thank you for your work for the PHP community.

Best regards

**Comment by oerdnj** [comment]
It is still incomplete...  see the issue template for more details, those are also good guidelines for debugging.

Nevertheless, you are doing something wrong on your side, because the packages are in fact available:

https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=mcrypt&field.status_filter=published&field.series_filter=focal
