### ISSUE TITLE
PHP 8.1.22 pcntl_waitpid is broken

### ISSUE THREAD

**Issue by tlathm** [oerdnj/deb.sury.org#2007]
**Frequently asked questions**

- [x ] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x ] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x ] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
As per this PHP issue, PHP 8.1.22 broke the pcntl_waitpid:

https://github.com/php/php-src/issues/11916

That issue indicates that this has been fixed in the development branch though it's not clear what that commit is. I'm hoping there's a way that a patched version can be rolled out. Thanks!

**Comment by todeveni** [comment]
The fix is in these commits for 8.1 and 8.2, which just reverts old behaviour.
https://github.com/php/php-src/commit/f7be15dbadca9e5410b936a9db291a23c22e26da
https://github.com/php/php-src/commit/c59bfc8d9803c02fd2f881a804623c8b3fe5444e

PHP 8.1.23 and 8.2.10 are scheduled for release thursday next week.

**Comment by oerdnj** [comment]
Patched and building
