### ISSUE TITLE
Why the php-7-zts launchpad repository is still marked as "experimental, unsupported"?

### ISSUE THREAD

**Issue by krocos** [oerdnj/deb.sury.org#277]
I want to use it in production with the pthreads extension, but these labels confuse me... :(

**Comment by oerdnj** [comment]
Because the repository is experimental and unsupported, and best effort only. f.e. the latest packages still fail to build and I haven't had time to fix the builds.

Also I don't understand why you did open the issue for this.

**Comment by krocos** [comment]
Sorry for that I asked the question here, but I got answer quickly :) Really sorry for that. I never do it again...

**Comment by robfrawley** [comment]
@krocos: Enabling ZTS introduces a large collection of possible (and often likely) failure points, generally to users not understanding the implications of this flag. Threading is tricky, and relatively untested in the PHP world. I too use ZTS builds at work for one of the projects, but I suspect oerdnj's builds will remain unsupported for quite some time (likely until (if) it achieves stability, momentum, and usage uptake).

Otherwise, there isn't much incentive for oerdnj to support a slew of users who want to play with threads and make a pthreads-enabled daemon that ultimately leaks memory and consumes their server's usable ram because they didn't spend the time to research implementation or shortcomings. I don't blame him, either: I wouldn't want to. ;-)

**Comment by krocos** [comment]
Well, @robfrawley, I share your point of view. Hope that the thread safety by default will not take long...
