### ISSUE TITLE
php-redis 2.2.5 in PPA PHP 7.0.4

### ISSUE THREAD

**Issue by thomasvargiu** [oerdnj/deb.sury.org#288]
The php-redis extension is 2.2.5 and not 2.2.7. 
This is not compatible with PHP 7.

EDIT:
Thanks to @fntlnz for details

**Comment by fntlnz** [comment]
[Here](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=redis&field.status_filter=published&field.series_filter=) The indicated version is `2.2.7`.

If you download any one of the available packages (deb, tar, etc..) and decompress it, two folders will be created namely `php-5.6` and `php-7.0`.

The php-5.6 folder contains:

php-5.6/redis-2.2.7/php_redis.h
```
#define PHP_REDIS_VERSION "2.2.7"
```

while the php-7.0 folder contains:

php-redis_2.2.7-355-g799e0bc+2.2.7.orig/php-7.0/redis-2.2.7-355-g799e0bc/php_redis.h
```
#define PHP_REDIS_VERSION "2.2.5"
```

The problem is that `PHP_REDIS_VERSION` is not `2.2.7` in PHP 7.

**Comment by oerdnj** [comment]
So no problem here in fact. Just bad upstream numbering.

**Comment by fntlnz** [comment]
@oerdnj What do you mean? The problem is not only that the `PHP_REDIS_VERSION` is set to `2.2.5` running a php -ri redis shows that the installed phpredis version is actually `2.2.5` while should be `2.2.7`

**Comment by oerdnj** [comment]
So what? Why does version number matter so much? It's just a random string in the source code. You are running experimental git code anyway, since there's no redis release for PHP 7.0

**Comment by enoch85** [comment]
@fntlnz If you want Redis on PHP 7 you have to install it like this: https://github.com/enoch85/ownCloud-VM/blob/master/beta/install-redis-php-7.sh

**Comment by oerdnj** [comment]
@enoch85 How is that different from `php-redis` package? Please stop canibalizing issues here for your own cause.

**Comment by enoch85** [comment]
@oerdnj My intention was to help, sorry if you feel like I cannibalizing this repo. 

Ofc the best solution would be if php-redis was 2.2.7 or later. But reading this issue it seems like it's not and that's why I posted a solution.

**Comment by oerdnj** [comment]
This is the problem:
```
$ grep -r PHP_REDIS_VERSION php-*
php-5.6/redis-2.2.7/php_redis.h:#define PHP_REDIS_VERSION "2.2.7"
php-5.6/redis-2.2.7/redis.c:     PHP_REDIS_VERSION,
php-5.6/redis-2.2.7/redis.c:    php_info_print_table_row(2, "Redis Version", PHP_REDIS_VERSION);
php-7.0/redis-2.2.7-355-g799e0bc/php_redis.h:#define PHP_REDIS_VERSION "2.2.5"
php-7.0/redis-2.2.7-355-g799e0bc/redis.c:     PHP_REDIS_VERSION,
php-7.0/redis-2.2.7-355-g799e0bc/redis.c:    php_info_print_table_row(2, "Redis Version", PHP_REDIS_VERSION);
```
That just got fixed in upstream git.
