### ISSUE TITLE
Please move apt-listchanges from Depends to Suggests or Recommends

### ISSUE THREAD

**Issue by vegarnilsen** [oerdnj/deb.sury.org#308]
Hi, please reconsider adding apt-listchanges as a dependency to php5. We update all our servers through a fabric script, and this change introduces a new prompt for confirmation during the upgrade. As apt-listchanges is a dependency we can't remove it, since that also removes the PHP packages, so now we get this confirmation request on all upgrades on a lot of servers.

**Comment by oerdnj** [comment]
It's quite easy to disable the prompt.

1. Configure apt-listchanges somewhere to desired state:
`dpkg-reconfigure -p low apt-listchanges`

2. Dump the configuration (Install `debconf-utils` if `debconf-get-selections` is not available on the machine):
`debconf-get-selections | grep ^apt-listchanges > apt-listchanges.debconf-preseed`

This should create something like this:
```
apt-listchanges	apt-listchanges/which	select	news
apt-listchanges	apt-listchanges/email-address	string	<your_email_address>
apt-listchanges	apt-listchanges/confirm	boolean	false
apt-listchanges	apt-listchanges/frontend	select	mail
apt-listchanges	apt-listchanges/save-seen	boolean	true
```

3. Prior to installation preseed debconf database:
`< apt-listchanges.debconf-preseed | debconf-set-selection`

That said, I will probably move apt-listchanges to Recommends: in the next upload as this was more an experiment, because I found out nobody reads NEWS.Debian unless really forced.

**Comment by oerdnj** [comment]
Moved to Recommends
