### ISSUE TITLE
[feature]: arm64 packages in the Debian repository

### ISSUE THREAD

**Issue by akatasonov** [oerdnj/deb.sury.org#421]
Hi Ondrej!

Thank you very much for the excellent PHP repo - it is a pleasure to use. Curious if you are planning to provide arm64 packages.

**Comment by oerdnj** [comment]
Have you even tried? The arm64 is enabled where available

**Comment by akatasonov** [comment]
apt-get update for a Debian Jessie repo results in
`W: Failed to fetch https://packages.sury.org/php/dists/jessie/InRelease  Unable to find expected entry 'main/binary-arm64/Packages' in Release file (Wrong sources.list entry or malformed file)`

**Comment by oerdnj** [comment]
Ok, that's different thing. Could you please specify what exactly your problem is next time?

I don't provide arm64 packages packages for Debian, as I don't have a qemubuilder setup in place (yet). This is something I will look into in future when I have some free time available.

I'll reopen (and rename) the issue to keep the track.

**Comment by oerdnj** [comment]
And of course if anybody has a reliable way how to plug qemubuilder into jenkins-debian-glue, I would be happy to hear about it.

**Comment by oerdnj** [comment]
dup of #579
