### ISSUE TITLE
libapache2-mod-php5.5 missing from repository

### ISSUE THREAD

**Issue by joshbaldock** [oerdnj/deb.sury.org#506]
Was testing a process of upgrading apache 2.2 to apache 2.4 on a test system a few hours ago using your repositories where the libapache2-mod-php5.5 package was being installed. Now when I try the same processes, it seems that the package is missing.

Can you please advise if this is intentional? Or and issue?

Expecting below commands will install apache 2.4 and libapache2-mod-php5.5:
```
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/apache2
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install apache2 libapache2-mod-php5.5
```

Repository now reports package libapache2-mod-php5.5 as not found.

**Comment by oerdnj** [comment]
https://www.patreon.com/posts/php-5-5-end-of-7174814
https://twitter.com/debsuryorg/status/795007836791205888
https://twitter.com/debsuryorg/status/806881207413862400
https://twitter.com/debsuryorg/status/808284372356825088

PHP 5.5 was EOLed almost 5 months ago and does not receive any security updates since then: http://php.net/eol.php
