### ISSUE TITLE
php-gettext old php Class Constructor

### ISSUE THREAD

**Issue by ma11011s** [oerdnj/deb.sury.org#603]
php-gettext uses old php Class Constructors.

fix is available here:
https://bugs.launchpad.net/php-gettext/+bug/1522900

extra info:
https://askubuntu.com/questions/796135/depreciation-notice-error-in-phpmyadmin-with-16-04/796705#796705

**Comment by oerdnj** [comment]
I don't provide PHP application or PHP libraries (e.g. written in PHP) in the PPA (except for php-pear package).

**Comment by peterthomassen** [comment]
@oerdnj I am not fully following -- this page shows that your PPA contains a `php-gettext` package.

In Ubuntu, `php7.0-common` provides `php-gettext`, on which phpmyadmin depends. Your `php7.0-common`, however, does not provide this package, so installing phpmyadmin in conjunction with your PPA leads to `php-gettext` being installed from your PHP, which, however, is incompatible with PHP 7 because of the constructors.

Don't you think it makes sense to fix this? There is also an upstream fix: https://bugs.launchpad.net/php-gettext/+bug/1522900/comments/12

**Comment by oerdnj** [comment]
@peterthomassen You can use https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin for up to date phpmysqladmin packages that should not have the problem.
