### ISSUE TITLE
php7.0 7.0.21-1~ubuntu14.04.1+deb.sury.org+1 now depends on libssl1.1

### ISSUE THREAD

**Issue by fancycode** [oerdnj/deb.sury.org#643]
The previous version 7.0.20 had a dependency on libssl1.0.2, this has now changed to libssl1.1 (for example in `libapache2-mod-php7.0`).

Is this a hard requirement for php 7.0.21? I would rather not update my libssl to a new major version to get a minor version upgrade of php7.0.

**Comment by oerdnj** [comment]
You are not upgrading this system wide, just for PHP.

**Comment by eguaj** [comment]
`libssl` might not be system-wide, but` openssl` is system-wide: the `/usr/bin/openssl` binary was changed and some additional commands (located in` /usr/lib/ssl/misc/*`) have been removed :

```
Removed:
[x] "/usr/lib/ssl/misc/CA.sh"
[x] "/usr/lib/ssl/misc/c_hash"
[x] "/usr/lib/ssl/misc/c_info"
[x] "/usr/lib/ssl/misc/c_issuer"
[x] "/usr/lib/ssl/misc/c_name"
```

Also, upgrading with `--auto-remove` was a bad idea (from my part) as `libssl-1.0.2l` was removed and it broke a manually installed Rail app which apparently got linked against this specific version...

I also tend to be extra wary when it comes to openssl/libssl upgrades because I got bitten multiples times in the past, and I still get bitten once in a while :-)

**Comment by oerdnj** [comment]
https://help.ubuntu.com/community/PinningHowto
