### ISSUE TITLE
PHP 5.3 for Ubuntu 14.04

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#79]
Redirected from #15

**Comment by JeGr** [comment]
To bring it over, my/our idea for an "old" build of PHP 5.3 for Trusty was to take - if possible - the last version of PHP 5.3 and use the Debian & Ubuntu Patches from the Precise packages, that the security team is still maintaining until 04/2017.
Would that be an adequate intermediate solution until Precise EOL to have the an old version running "relatively" safe - and of course - is that a workable solution?

**Comment by oerdnj** [comment]
@pbowyer @JeGr To be honest, I am not very inclined to do this, since I consider running PHP 5.3 as a security risk, but if you know about that, it would be your risk. However as this requires a quite amount of work to forward port PHP 5.3 to new packaging infrastructure, it will need some funding. We should probably discuss that off-line.

Also I probably wouldn't be able to pro-actively watch security problems in PHP 5.3 due E_NOTENOUGHFREETIME, so somebody would need to act as a "security team" and notify me about serious security risks.

**Comment by JeGr** [comment]
@oerdnj already sent you email to your @sury.org address.
What are you considering as security risk with 5.3? Just curious, as the packages from precise are still maintained by the ubuntu security team and got various small upgrades over the last weeks, so I tend to consider them "relatively" safe. That was the reason we came up with the idea of re-using those patches (why invent the wheel a second time) ;)
As one gets the security updates for precise/php53, that should be possible to send you a ping for new patches from the team.
And last but not least considering funding - feel free to throw around some numbers here or via mail, but I think @pbowyer and others might perhaps be interested, too. ATM I could only find one project over at launchpad for old PHP on trusty and his packages are build twice last year and since then - nothing. So a moderately maintained version is better than none at all :)

**Comment by pbowyer** [comment]
Re funding, being able to do this was the reason I pledged on #15 and encouraged others to do so - I totally understand the need for funding.

I wasn't aware of a new packaging infrastructure, that's a bummer.

**Comment by oerdnj** [comment]
I see these tasks here:
 
- forward porting PHP 5.3 packaging to Apache 2.4 (and other libraries)
- forward porting PHP 5.3 itself to Apache 2.4 (as far as I remember there might be some incompatibilites, but I have no idea right now)
- forward porting FPM in PHP 5.3, so php5-fpm is available

I would like to keep the exact number in private, but since this is not something I would do for the community, this would have to be contractual work and it would be more costly than #15 or #16.

**Comment by JeGr** [comment]
Would it be an easier task if one were to exclude specific Apache dependencies? I don't know others but all we need would be a FPM build to work. That would also be useful for working with other Servers like NGINX. I see mentions that mod_php's still faster in some setups, but Apache2.4/NGinx and FPM tested nearly as fast (or even faster) in our setup, so we've no direct need for Apache bindings. Just sayin'

The other point is how we should proceed in terms of funding. If this is kept here on GitHub and in this issue I doubt it would gain much momentum besides a few people already knowing this or issue #15 so how about some publicity or even try a funding tool like KS/IGG/whatever? With a few mentions on lists and newsletters that may gain some attraction?

**Comment by JeGr** [comment]
Another point would be: how many are already willing now to pitch in? And how about the idea of some Kickstarting?

**Comment by fajarnugraha** [comment]
@JeGr recommends to port precise/php53 (which probably work security-wise until precise is EOLed April 2017). However, as a suggestion, wouldn't it be easier and faster to run a precise container for php53 instead? e.g:

- use trusty as host
- install nginx and other needed packages (other than php) directly on the host (or in their own trusty container)
- install php-5.3 in its own precise container, AND harden it so that basically the only running service there is php-fpm
- do any other user interaction (e.g. uploading file via ssh/sftp) from the host (or another specialized trusty container sharing the same data directory)

It should be easy enough to setup, and all developer/community resource could be redirected to other efforts (e.g. #15)

**Comment by JeGr** [comment]
@fajarnugraha Simple: Because not everyone is keen on running containers for everything that can be simply done by running the same thing in the machine environment. Introducing containers of some sort (docker et al) would consist of bringing unneeded complexity and additional overhead to a machine that could simply be avoided by just installing the right version of the needed package. As we discuss live and production machines here, there is no need for multiple php versions (that would be a thing for docker, alright).
